"""setting project code to unique

Revision ID: 950ed3b91911
Revises: ea728e355edd
Create Date: 2025-12-09 16:17:26.776150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950ed3b91911'
down_revision: Union[str, Sequence[str], None] = 'ea728e355edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'projects', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    # ### end Alembic commands ###
