"""setting provider rfc property to unique

Revision ID: 9b499d236a70
Revises: fc483d57aed1
Create Date: 2025-12-09 18:44:01.501359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b499d236a70'
down_revision: Union[str, Sequence[str], None] = 'fc483d57aed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'providers', ['rfc'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'providers', type_='unique')
    # ### end Alembic commands ###
