"""setting user approved_by -> reviewed_by for more comprehesing

Revision ID: ee499d5ee6b5
Revises: 34521d839f53
Create Date: 2025-12-10 00:44:36.997351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee499d5ee6b5'
down_revision: Union[str, Sequence[str], None] = '34521d839f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.alter_column('expenses', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('expenses', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(op.f('expenses_approved_by_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'users', ['reviewed_by_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('expenses', 'approved_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('approved_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_approved_by_id_fkey'), 'expenses', 'users', ['approved_by_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('expenses', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('expenses', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('expenses', 'reviewed_by_id')
    # ### end Alembic commands ###
