"""setting bank account number property to uniuqe

Revision ID: fc483d57aed1
Revises: 950ed3b91911
Create Date: 2025-12-09 17:55:19.818350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc483d57aed1'
down_revision: Union[str, Sequence[str], None] = '950ed3b91911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bank_accounts', ['account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_accounts', type_='unique')
    # ### end Alembic commands ###
